CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT ck_categories_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_categories_slug_normalized
        CHECK (slug = lower(btrim(slug)) AND slug <> '')
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    short_description TEXT,
    description TEXT,
    thumbnail_url TEXT,
    sale_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT uq_products_slug UNIQUE (slug),
    CONSTRAINT ck_products_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_products_slug_normalized
        CHECK (slug = lower(btrim(slug)) AND slug <> ''),
    CONSTRAINT ck_products_thumbnail_url
        CHECK (thumbnail_url IS NULL OR thumbnail_url ~ '^https://'),
    CONSTRAINT ck_products_sale_type
        CHECK (sale_type IN ('FIXED_PRICE', 'QUOTE')),
    CONSTRAINT ck_products_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    sku VARCHAR(50),
    price BIGINT,
    min_quantity NUMERIC NOT NULL,
    quantity_step NUMERIC NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_product_variants_sku UNIQUE (sku),
    CONSTRAINT ck_product_variants_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_product_variants_sku_normalized
        CHECK (sku IS NULL OR (sku = btrim(sku) AND sku <> '')),
    CONSTRAINT ck_product_variants_price
        CHECK (price IS NULL OR price BETWEEN 0 AND 9000000000000),
    CONSTRAINT ck_product_variants_min_quantity
        CHECK (
            min_quantity BETWEEN 0.01 AND 99999999.99
            AND scale(min_quantity) <= 2
        ),
    CONSTRAINT ck_product_variants_quantity_step
        CHECK (
            quantity_step BETWEEN 0.01 AND 99999999.99
            AND scale(quantity_step) <= 2
        )
);

CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value BIGINT NOT NULL,
    max_discount BIGINT,
    min_order_value BIGINT NOT NULL DEFAULT 0,
    quantity INTEGER NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    start_at TIMESTAMPTZ,
    end_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vouchers_code UNIQUE (code),
    CONSTRAINT ck_vouchers_code_normalized
        CHECK (code = upper(btrim(code)) AND code <> ''),
    CONSTRAINT ck_vouchers_discount_type
        CHECK (discount_type IN ('FIXED', 'PERCENT')),
    CONSTRAINT ck_vouchers_discount CHECK (
        discount_type NOT IN ('FIXED', 'PERCENT')
        OR (
            discount_value > 0
            AND discount_value <= 9000000000000
            AND (
                (discount_type = 'FIXED' AND max_discount IS NULL)
                OR
                (discount_type = 'PERCENT' AND discount_value <= 100)
            )
        )
    ),
    CONSTRAINT ck_vouchers_max_discount
        CHECK (max_discount IS NULL OR max_discount BETWEEN 0 AND 9000000000000),
    CONSTRAINT ck_vouchers_min_order_value
        CHECK (min_order_value BETWEEN 0 AND 9000000000000),
    CONSTRAINT ck_vouchers_usage
        CHECK (quantity >= 0 AND used_count >= 0 AND used_count <= quantity),
    CONSTRAINT ck_vouchers_time_window
        CHECK (start_at IS NULL OR end_at IS NULL OR start_at < end_at)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(30) NOT NULL,
    order_type VARCHAR(20) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address TEXT,
    subtotal BIGINT,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    total_amount BIGINT,
    voucher_id BIGINT,
    voucher_code_snapshot VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    customer_note TEXT,
    admin_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_voucher
        FOREIGN KEY (voucher_id) REFERENCES vouchers (id),
    CONSTRAINT uq_orders_order_code UNIQUE (order_code),
    CONSTRAINT ck_orders_order_type
        CHECK (order_type IN ('ORDER', 'QUOTE_REQUEST')),
    CONSTRAINT ck_orders_order_code CHECK (
        order_type NOT IN ('ORDER', 'QUOTE_REQUEST')
        OR (order_type = 'ORDER' AND order_code ~ '^DH-[0-9]{8}-[0-9]+$')
        OR (order_type = 'QUOTE_REQUEST' AND order_code ~ '^BG-[0-9]{8}-[0-9]+$')
    ),
    CONSTRAINT ck_orders_customer_name
        CHECK (customer_name = btrim(customer_name) AND customer_name <> ''),
    CONSTRAINT ck_orders_phone
        CHECK (phone ~ '^0[0-9]{9}$' OR phone ~ '^\+84[0-9]{9}$'),
    CONSTRAINT ck_orders_address
        CHECK (address IS NULL OR (address = btrim(address) AND address <> '' AND length(address) <= 1000)),
    CONSTRAINT ck_orders_customer_note
        CHECK (customer_note IS NULL OR length(customer_note) <= 2000),
    CONSTRAINT ck_orders_admin_note
        CHECK (admin_note IS NULL OR length(admin_note) <= 2000),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('NEW', 'CONTACTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_orders_voucher_snapshot CHECK (
        order_type NOT IN ('ORDER', 'QUOTE_REQUEST')
        OR order_type = 'QUOTE_REQUEST'
        OR (voucher_id IS NULL) = (voucher_code_snapshot IS NULL)
    ),
    CONSTRAINT ck_orders_voucher_code_normalized
        CHECK (
            voucher_code_snapshot IS NULL
            OR (voucher_code_snapshot = upper(btrim(voucher_code_snapshot))
                AND voucher_code_snapshot <> '')
        ),
    CONSTRAINT ck_orders_amounts_by_type CHECK (
        order_type NOT IN ('ORDER', 'QUOTE_REQUEST')
        OR (
            order_type = 'ORDER'
            AND subtotal IS NOT NULL
            AND total_amount IS NOT NULL
            AND subtotal BETWEEN 0 AND 9000000000000
            AND discount_amount BETWEEN 0 AND subtotal
            AND total_amount = subtotal - discount_amount
        )
        OR (
            order_type = 'QUOTE_REQUEST'
            AND subtotal IS NULL
            AND total_amount IS NULL
            AND discount_amount = 0
            AND voucher_id IS NULL
            AND voucher_code_snapshot IS NULL
        )
    )
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    variant_id BIGINT,
    product_name_snapshot VARCHAR(150) NOT NULL,
    variant_name_snapshot VARCHAR(100),
    quantity NUMERIC NOT NULL,
    unit_price BIGINT,
    line_total BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_order_items_variant
        FOREIGN KEY (variant_id) REFERENCES product_variants (id),
    CONSTRAINT ck_order_items_product_name
        CHECK (btrim(product_name_snapshot) <> ''),
    CONSTRAINT ck_order_items_variant_name
        CHECK (variant_name_snapshot IS NULL OR btrim(variant_name_snapshot) <> ''),
    CONSTRAINT ck_order_items_quantity CHECK (
        quantity BETWEEN 0.01 AND 99999999.99
        AND scale(quantity) <= 2
    ),
    CONSTRAINT ck_order_items_amounts CHECK (
        quantity NOT BETWEEN 0.01 AND 99999999.99
        OR scale(quantity) > 2
        OR (
            (unit_price IS NULL AND line_total IS NULL)
            OR (
                unit_price IS NOT NULL
                AND line_total IS NOT NULL
                AND unit_price BETWEEN 0 AND 9000000000000
                AND line_total BETWEEN 0 AND 9000000000000
                AND line_total = unit_price * quantity
            )
        )
    )
);

CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_admins_email UNIQUE (email),
    CONSTRAINT ck_admins_email_normalized
        CHECK (email = lower(btrim(email)) AND email <> ''),
    CONSTRAINT ck_admins_password_hash CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_admins_name CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_status ON products (status);
CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);
CREATE INDEX idx_orders_voucher_id ON orders (voucher_id);
CREATE INDEX idx_orders_phone ON orders (phone);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_created_at ON orders (created_at);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
CREATE INDEX idx_order_items_variant_id ON order_items (variant_id);

CREATE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_product_variants_updated_at
BEFORE UPDATE ON product_variants
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_vouchers_updated_at
BEFORE UPDATE ON vouchers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_admins_updated_at
BEFORE UPDATE ON admins
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
