CREATE TABLE sheet_sync_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY', 'SUCCEEDED')),
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_error VARCHAR(200),
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at TIMESTAMPTZ,
    locked_by VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sheet_sync_lease CHECK (
        (status = 'PROCESSING' AND locked_at IS NOT NULL AND locked_by IS NOT NULL)
        OR (status <> 'PROCESSING' AND locked_at IS NULL AND locked_by IS NULL)
    )
);
CREATE INDEX idx_sheet_sync_due ON sheet_sync_jobs(next_retry_at, id) WHERE status IN ('PENDING', 'RETRY');
CREATE INDEX idx_sheet_sync_lease ON sheet_sync_jobs(locked_at, id) WHERE status = 'PROCESSING';
CREATE INDEX idx_sheet_sync_order_pending ON sheet_sync_jobs(order_id, id) WHERE status <> 'SUCCEEDED';
CREATE TRIGGER trg_sheet_sync_updated_at BEFORE UPDATE ON sheet_sync_jobs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
INSERT INTO sheet_sync_jobs(order_id) SELECT id FROM orders ORDER BY id;
