ALTER TABLE products ADD COLUMN images_revision BIGINT NOT NULL DEFAULT 0 CHECK (images_revision >= 0);
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    url TEXT NOT NULL CHECK (url ~ '^https://'),
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    UNIQUE (product_id, url),
    UNIQUE (product_id, sort_order)
);
INSERT INTO product_images (product_id, url, sort_order)
SELECT id, thumbnail_url, 0 FROM products WHERE thumbnail_url IS NOT NULL;
