spring:
  config:
    activate:
      on-profile: test
  main:
    banner-mode: off
  datasource:
    password: ${DB_PASSWORD:oil_shop_test}

server:
  servlet:
    session:
      cookie:
        secure: false

logging:
  level:
    root: WARN
    com.shop: INFO
