spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: false
  datasource:
    password: ${DB_PASSWORD:oil_shop_local}

server:
  servlet:
    session:
      cookie:
        secure: false

logging:
  level:
    com.shop: DEBUG
