import { test, expect } from '@playwright/test';
import { signIn } from './admin-helper';

test.describe('Real catalog and media administration', () => {
  test.skip(process.env.PLAN10_REAL_BACKEND !== '1', 'Run npm run test:admin:e2e for disposable Spring/PostgreSQL');
  test('creates catalog, preserves expired drafts, uploads without saving, hides and reactivates', async ({ page, context }) => {
    test.setTimeout(90_000);
    const suffix = `${Date.now()}-${test.info().project.name}`;
    const category = `Danh mục ${suffix}`;
    const product = `Dầu ${suffix}`;
    await signIn(page);
    await page.getByRole('link', { name: 'Danh mục', exact: true }).click();
    await page.getByRole('button', { name: 'Tạo danh mục', exact: true }).click();
    await page.getByLabel('Tên danh mục', { exact: true }).fill(category);
    await page.getByLabel('Slug', { exact: true }).fill(`cat-${suffix}`);
    await page.getByRole('button', { name: 'Lưu danh mục', exact: true }).click();
    await expect(page.getByRole('heading', { name: category, exact: true })).toBeVisible();
    await page.getByLabel('Mô tả danh mục').fill('Bản nháp cần giữ');
    await context.clearCookies();
    await page.getByRole('button', { name: 'Lưu danh mục', exact: true }).click();
    const recovery = page.getByRole('dialog', { name: 'Đăng nhập lại' });
    await expect(recovery).toBeVisible();
    await recovery.getByLabel('Email quản trị').fill(process.env.PLAN10_ADMIN_EMAIL!);
    await recovery.getByLabel('Mật khẩu').fill(process.env.PLAN10_ADMIN_PASSWORD!);
    await recovery.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
    await expect(recovery).toBeHidden();
    await expect(page.getByLabel('Mô tả danh mục')).toHaveValue('Bản nháp cần giữ');
    await page.getByRole('button', { name: 'Lưu danh mục', exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: 'Đã lưu' })).toBeVisible();
    await page.getByRole('link', { name: 'Sản phẩm', exact: true }).click();
    await page.getByRole('button', { name: 'Tạo sản phẩm', exact: true }).click();
    await page.getByRole('combobox', { name: /^Danh mục/ }).selectOption({ label: category });
    await page.getByLabel('Tên sản phẩm', { exact: true }).fill(product);
    await page.getByLabel('Slug sản phẩm').fill(`oil-${suffix}`);
    await page.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await expect(page).toHaveURL(/\/admin\/products\/\d+$/);
    await expect(page.getByText('Chưa có quy cách đang bán.', { exact: false })).toBeVisible();
    const id = new URL(page.url()).pathname.split('/').pop()!;
    const newVariant = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Thêm quy cách', exact: true }) });
    await newVariant.getByLabel('Tên quy cách', { exact: true }).fill('Theo cân');
    await newVariant.getByLabel('SKU', { exact: true }).fill(`SKU-${suffix}`);
    await newVariant.getByLabel('Giá (VND)', { exact: true }).fill('1000');
    await newVariant.getByLabel('Số lượng tối thiểu').fill('0.5');
    await newVariant.getByLabel('Bước số lượng').fill('0.5');
    await newVariant.getByRole('button', { name: 'Lưu quy cách', exact: true }).click();
    const existing = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Quy cách: Theo cân', exact: true }) });
    await expect(existing).toBeVisible();
    await existing.getByRole('button', { name: 'Ẩn quy cách', exact: true }).click();
    await expect(existing.getByRole('button', { name: 'Kích hoạt quy cách' })).toBeVisible();
    await existing.getByRole('button', { name: 'Kích hoạt quy cách' }).click();
    await expect(existing.getByRole('button', { name: 'Ẩn quy cách', exact: true })).toBeVisible();
    const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
    await page.route('https://media.example.test/**', (route) => route.fulfill({ contentType: 'image/png', body: image }));
    const csrf = await (await page.request.get('/api/v1/csrf')).json();
    const headers = { Origin: new URL(page.url()).origin, [csrf.headerName]: csrf.token };
    const atLimit = Buffer.alloc(5 * 1024 * 1024); image.copy(atLimit);
    const limitUpload = await page.request.post('/api/v1/admin/media', { headers, multipart: { file: { name: 'limit.png', mimeType: 'image/png', buffer: atLimit } } });
    expect(limitUpload.status()).toBe(201);
    const tooLarge = await page.request.post('/api/v1/admin/media', { headers, multipart: { file: { name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(5 * 1024 * 1024 + 1) } } });
    expect(tooLarge.status()).toBe(413);
    const proxyTooLarge = await page.request.post('/api/v1/admin/media', { headers, multipart: { file: { name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(6 * 1024 * 1024 + 1) } } });
    expect(proxyTooLarge.status()).toBe(413);
    expect(await proxyTooLarge.json()).toMatchObject({ code: 'REQUEST_TOO_LARGE', fieldErrors: {}, traceId: expect.any(String) });
    const before = await (await page.request.get(`/api/v1/admin/products/${id}`)).json();
    await page.getByLabel('Chọn ảnh sản phẩm').setInputFiles({ name: 'oil.png', mimeType: 'image/png', buffer: image });
    await page.getByRole('button', { name: 'Tải ảnh lên', exact: true }).click();
    await expect(page.getByText('Đã tải ảnh lên.', { exact: false })).toBeVisible();
    const uploaded = await page.getByLabel('URL ảnh đại diện').inputValue();
    expect(uploaded).toContain('https://media.example.test/storage/v1/object/public/catalog/products/');
    const afterUpload = await (await page.request.get(`/api/v1/admin/products/${id}`)).json();
    expect(afterUpload.thumbnailUrl).toBe(before.thumbnailUrl);
    await page.route(`**/api/v1/admin/products/${id}`, async (route) => {
      if (route.request().method() === 'PUT') { await route.fulfill({ status: 503, json: { code: 'SERVICE_UNAVAILABLE', message: 'Temporary failure', fieldErrors: {}, traceId: 'test' } }); return; }
      await route.continue();
    });
    await page.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await expect(page.getByRole('alert').filter({ hasText: 'Không lưu được' })).toBeVisible();
    await expect(page.getByLabel('URL ảnh đại diện')).toHaveValue(uploaded);
    await expect(page.getByRole('button', { name: 'Lưu sản phẩm', exact: true })).toBeDisabled();
    await page.unroute(`**/api/v1/admin/products/${id}`);
    await page.getByRole('button', { name: 'Tải phiên bản đã lưu để đối chiếu' }).click();
    await page.getByRole('button', { name: 'Giữ bản nháp và cho phép lưu lại' }).click();
    await page.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: 'Đã lưu' })).toBeVisible();
    expect((await (await page.request.get(`/api/v1/admin/products/${id}`)).json()).thumbnailUrl).toBe(uploaded);
    expect(await page.getByRole('img', { name: 'Ảnh 1 trong bản nháp' }).evaluate((element) => (element as HTMLImageElement).naturalWidth)).toBe(1);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath('admin-product.png'), fullPage: true });
    expect((await (await page.request.get(`/api/v1/products/${`oil-${suffix}`}`)).json()).name).toBe(product);
    await page.getByLabel('Chọn ảnh sản phẩm').setInputFiles([
      { name: 'second.png', mimeType: 'image/png', buffer: image },
      { name: 'third.png', mimeType: 'image/png', buffer: image },
    ]);
    await page.getByRole('button', { name: 'Tải ảnh lên', exact: true }).click();
    await expect(page.getByRole('img', { name: 'Ảnh 3 trong bản nháp' })).toBeVisible();
    await page.getByRole('button', { name: 'Đưa ảnh 3 lên' }).click();
    await page.getByRole('button', { name: 'Chọn ảnh 2 làm đại diện' }).click();
    const newCover = await page.getByLabel('URL ảnh đại diện').inputValue();
    await page.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await expect.poll(async () => (await (await page.request.get(`/api/v1/admin/products/${id}`)).json()).thumbnailUrl).toBe(newCover);
    const galleryData = await (await page.request.get(`/api/v1/products/oil-${suffix}`)).json();
    expect(galleryData.images).toHaveLength(3);
    expect(galleryData.images[1].url).toBe(newCover);
    await page.goto(`/products/oil-${suffix}`);
    const publicThumbnail = page.getByRole('img', { name: `${product} — ảnh 1 trên 3`, exact: true });
    await expect(publicThumbnail).toHaveAttribute('src', uploaded);
    await expect.poll(() => publicThumbnail.evaluate((element) => (element as HTMLImageElement).naturalWidth)).toBe(1);
    const gallery = page.getByRole('region', { name: `Ảnh sản phẩm ${product}` });
    await page.getByRole('button', { name: 'Ảnh tiếp theo' }).click();
    await expect(gallery.getByRole('img')).toHaveAttribute('src', galleryData.images[1].url);
    await page.getByRole('button', { name: 'Xem ảnh 3' }).click();
    await expect(gallery.getByRole('img')).toHaveAttribute('src', galleryData.images[2].url);
    await page.screenshot({ path: test.info().outputPath('product-gallery.png'), fullPage: true });
    await page.goto('/admin/categories');
    await page.getByRole('button', { name: `Ẩn ${category}`, exact: true }).click();
    await expect(page.getByRole('button', { name: `Kích hoạt ${category}`, exact: true })).toBeVisible();
    expect((await page.request.get(`/api/v1/products/oil-${suffix}`)).status()).toBe(404);
    await page.getByRole('button', { name: `Kích hoạt ${category}`, exact: true }).click();
    await expect(page.getByRole('button', { name: `Ẩn ${category}`, exact: true })).toBeVisible();
    expect((await page.request.get(`/api/v1/products/oil-${suffix}`)).status()).toBe(200);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath('admin-categories.png'), fullPage: true });
  });
});
